### ISSUE TITLE
RuntimeError: Compression failed: Broken pipe 

### ISSUE THREAD

**Issue by btm** [mjackson/yuicompressor#2]
yuicompressor appears to be dying on an EC2 m1.small instance running under nanoc. It fails at a different place each run and never seems to successfully complete.

Ubuntu 10.04.3 LTS (lucid) 
Ruby 1.8.7.249-2ubuntu0.1 (from distribution packages)
Rubygems 1.6.2 (from source)
bundler 1.1.3
yuicompressor 1.2.0

This may be related to the [java memory error in yui-compressor](https://github.com/sstephenson/ruby-yui-compressor/issues/19).

```
$ bundle exec rake compile

[snip]

Captain! We’ve been hit!

=== MESSAGE:

RuntimeError: Compression failed: Broken pipe

=== COMPILATION STACK:

  (empty)

=== BACKTRACE:

  0. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/yuicompressor-1.2.0/lib/yuicompressor/shell.rb:65:in `compress'
  1. /usr/lib/ruby/1.8/open3.rb:86:in `popen3'
  2. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/yuicompressor-1.2.0/lib/yuicompressor/shell.rb:56:in `compress'
  3. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/nanoc-3.3.2/lib/nanoc/filters/yui_compressor.rb:18:in `run'
  4. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/nanoc-3.3.2/lib/nanoc/base/result_data/item_rep.rb:344:in `filter'
  5. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/nanoc-3.3.2/lib/nanoc/base/compilation/item_rep_proxy.rb:47:in `filter'
  6. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/nanoc-3.3.2/lib/nanoc/base/compilation/rule_context.rb:54:in `filter'
  7. ./Rules:64:in `load'
  8. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/nanoc-3.3.2/lib/nanoc/base/compilation/rule.rb:68:in `instance_eval'
  9. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/nanoc-3.3.2/lib/nanoc/base/compilation/rule.rb:68:in `apply_to'
  10. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/nanoc-3.3.2/lib/nanoc/base/compilation/compiler.rb:381:in `compile_rep'
  11. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/nanoc-3.3.2/lib/nanoc/base/compilation/compiler.rb:337:in `compile_reps'
  12. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/nanoc-3.3.2/lib/nanoc/base/compilation/compiler.rb:330:in `loop'
  13. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/nanoc-3.3.2/lib/nanoc/base/compilation/compiler.rb:330:in `compile_reps'
  14. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/nanoc-3.3.2/lib/nanoc/base/compilation/compiler.rb:85:in `run'
  15. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/nanoc-3.3.2/lib/nanoc/base/source_data/site.rb:57:in `compile'
  16. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/nanoc-3.3.2/lib/nanoc/cli/commands/compile.rb:57:in `run'
  17. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/nanoc-3.3.2/lib/nanoc/cli/command_runner.rb:14:in `call'
  18. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/nanoc-3.3.2/lib/nanoc/cli/error_handler.rb:42:in `handle_while'
  19. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/nanoc-3.3.2/lib/nanoc/cli/error_handler.rb:23:in `handle_while'
  20. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/nanoc-3.3.2/lib/nanoc/cli/command_runner.rb:13:in `call'
  21. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/cri-2.2.1/lib/cri/command_dsl.rb:175
  22. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/cri-2.2.1/lib/cri/command.rb:291:in `call'
  23. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/cri-2.2.1/lib/cri/command.rb:291:in `run_this'
  24. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/cri-2.2.1/lib/cri/command.rb:244:in `run'
  25. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/cri-2.2.1/lib/cri/command.rb:257:in `run'
  26. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/nanoc-3.3.2/lib/nanoc/cli.rb:44:in `run'
  27. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/nanoc-3.3.2/lib/nanoc/cli/error_handler.rb:42:in `handle_while'
  28. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/nanoc-3.3.2/lib/nanoc/cli/error_handler.rb:23:in `handle_while'
  29. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/nanoc-3.3.2/lib/nanoc/cli.rb:41:in `run'
  30. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/gems/nanoc-3.3.2/bin/nanoc:19
  31. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/bin/nanoc:19:in `load'
  32. /srv/opscode-corpsite/vendor/bundle/ruby/1.8/bin/nanoc:19

=== VERSION INFORMATION:

nanoc 3.3.2 © 2007-2012 Denis Defreyne.
Running ruby 1.8.7 (2010-01-10) on x86_64-linux with RubyGems 1.6.2.
```

**Comment by btm** [comment]
This was actually happening because Java was no longer installed due to the sun -> oracle shenanigans. I discovered this by adding a debugging statement before the popen3 block to print out the command that was going to be run.

**Comment by mjackson** [comment]
Thanks for looking further into this!
